Repository dnd-side-project/dnd-12th-7-frontend, pull requests merged in 2025-01, with the labels that each got.

#4 Issue와 PR 템플릿 추가
  .github/ISSUE_TEMPLATE/01-feature.md
  .github/ISSUE_TEMPLATE/02-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🖥️ FE, 📄 Document

#8 개발 환경 초기화, 폴더 구조 정의, SVGR 세팅
  .gitignore
  .svgrrc.yaml
  README.md
  eslint.config.js
  index.html
  package.json
  public/svgs/react.svg
  src/App.tsx
  src/assets/svgs/React.tsx
  src/assets/svgs/index.ts
  src/common/components/button/index.tsx
  src/common/components/header/index.tsx
  src/main.tsx
  src/mocks/test.ts
  src/pages/main/components/testComponent/index.tsx
  src/pages/main/index.tsx
  src/pages/main/styles/index.styles.ts
  src/pages/main/types/index.ts
  src/service/apis/user/index.ts
  src/stores/useTest.ts
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: ⚙️ Setting, Priority 1

#9 Issue와 PR 환경 설정
  .github/ISSUE_TEMPLATE/01-feature.md
  .github/ISSUE_TEMPLATE/02-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/sync-labels/.gitignore
  .github/actions/sync-labels/action.yml
  .github/actions/sync-labels/dist/index.js
  .github/actions/sync-labels/package.json
  .github/actions/sync-labels/src/index.js
  .github/actions/sync-labels/yarn.lock
  .github/workflows/pr-review-manager.yml
Labels: 🖥️ FE, ⚙️ Setting, 📄 Document

#11 필요한 패키지 설치, 정적 분석 도구와 PWA 초기 세팅
  .eslintignore
  .eslintrc.cjs
  .gitignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  eslint.config.js
  index.html
  package.json
  public/mockServiceWorker.js
  public/pwa/apple-touch-icon-180x180.png
  public/pwa/favicon.ico
  public/pwa/maskable-icon-512x512.png
  public/pwa/pwa-192x192.png
  public/pwa/pwa-512x512.png
  public/pwa/pwa-64x64.png
  src/App.tsx
  src/assets/svgs/React.tsx
  src/assets/svgs/index.ts
  src/common/components/button/Button.stories.ts
  src/common/components/button/Button.tsx
  src/common/components/button/button.css
  src/common/components/button/index.tsx
  src/common/components/header/Header.stories.ts
  src/common/components/header/Header.tsx
  src/common/components/header/header.css
  src/common/components/header/index.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/test.ts
  src/pages/main/components/testComponent/index.tsx
  src/pages/main/index.tsx
  src/pages/main/styles/index.styles.ts
  src/pages/main/types/index.ts
  src/service/apis/user/index.ts
  src/stores/useTest.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 🖥️ FE, ⚙️ Setting

#16 Zenhub 자동화 액션 추가
  .github/actions/.gitignore
  .github/actions/package.json
  .github/actions/setup-node/action.yml
  .github/actions/sync-labels/action.yml
  .github/actions/sync-labels/dist/index.js
  .github/actions/sync-labels/index.js
  .github/actions/utils/getIssueNumberFromBranch.js
  .github/actions/yarn.lock
  .github/actions/zenhub-move-issue/action.yml
  .github/actions/zenhub-move-issue/index.js
  .github/workflows/pr-review-manager.yml
  .github/workflows/zenhub-move-in-progress.yml
Labels: 🖥️ FE, ⚙️ Setting
