Repository dnd-side-project/dnd-12th-7-frontend, pull requests merged in 2025-04, with the labels that each got.

#119 첫 페이지 로딩 시간 개선
  package.json
  src/Router.tsx
  yarn.lock
Labels: 🖥️ FE, 🛠️ Refactor

#120 온보딩 페이지 로직 변경: 디바이스 환경에 따른 이동 방식 수정
  package.json
  src/common/components/Lottie/index.styles.ts
  src/common/components/Lottie/index.tsx
  src/pages/onboarding/index.style.ts
  src/pages/onboarding/index.tsx
  src/styles/globalStyles.ts
  src/vite-env.d.ts
  yarn.lock
Labels: 🖥️ FE, ✨ Feature, 🎨 Design

#124 경로를 케밥 케이스 표기로 통일
  src/common/constants/route.ts
Labels: 🖥️ FE, 🛠️ Refactor

#123 TODO 주석 정리
  src/common/components/StatusChip/index.type.ts
  src/common/constants/shareFormat.ts
  src/common/queries/expense/useDeleteExpense.ts
  src/stores/useTest.ts
  vite.config.ts
Labels: 🖥️ FE, 📄 Document

#122 SEO 적용을 위한 meta tag, robots.txt, sitemap 적용 및 home 페이지 url 변경
  index.html
  public/pngs/OGImage.png
  public/robots.txt
  public/sitemap.xml
  src/common/constants/route.ts
  src/pages/home/index.tsx
Labels: 🖥️ FE, 🛠️ Refactor
