Repository dnd-side-project/dnd-12th-7-frontend, pull requests merged in 2025-02, with the labels that each got.

#19 정산할 내역 입력 페이지 UI 구현
  .eslintrc.cjs
  .nvmrc
  package.json
  src/Router.tsx
  src/common/components/Chip.tsx
  src/common/components/header/Header.stories.ts
  src/common/components/header/Header.tsx
  src/common/components/header/header.css
  src/common/styles/Chip.styles.ts
  src/main.tsx
  src/pages/create/addBillStep/components/BillFormCard.tsx
  src/pages/create/addBillStep/components/BillFormField.tsx
  src/pages/create/addBillStep/index.tsx
  src/pages/create/addBillStep/styles/BillFormCard.styles.ts
  src/pages/create/addBillStep/styles/BillFormField.styles.ts
  src/pages/create/addBillStep/styles/index.styles.ts
  src/pages/create/index.tsx
  tsconfig.json
  yarn.lock
Labels: 🖥️ FE, ✨ Feature, Priority 1

#20 결제 금액 입력 키패드 UI 구현
  package.json
  src/common/components/Drawer/close-button.tsx
  src/common/components/Drawer/drawer.tsx
  src/pages/create/addBillStep/components/BillDatePicker/index.styles.tsx
  src/pages/create/addBillStep/components/BillDatePicker/index.tsx
  src/pages/create/addBillStep/components/BillFormCard.tsx
  src/pages/create/addBillStep/components/BillFormCard/index.styles.ts
  src/pages/create/addBillStep/components/BillFormCard/index.tsx
  src/pages/create/addBillStep/components/BillFormField/index.styles.ts
  src/pages/create/addBillStep/components/BillFormField/index.tsx
  src/pages/create/addBillStep/components/NumPad/index.styles.tsx
  src/pages/create/addBillStep/components/NumPad/index.tsx
  src/pages/create/addBillStep/components/NumPadBottomSheet/index.styles.ts
  src/pages/create/addBillStep/components/NumPadBottomSheet/index.tsx
  src/pages/create/addBillStep/components/ParticipantChips/index.styles.ts
  src/pages/create/addBillStep/components/ParticipantChips/index.tsx
  src/pages/create/addBillStep/components/ReadonlyInput/index.tsx
  src/pages/create/addBillStep/index.styles.ts
  src/pages/create/addBillStep/index.tsx
  src/pages/create/addBillStep/utils/numPadController.test.ts
  src/pages/create/addBillStep/utils/numPadController.ts
  yarn.lock
Labels: 🖥️ FE, ✨ Feature, Priority 1

#23 useFunnel 구현
  .eslintrc.cjs
  src/common/hooks/useFunnel.ts
  src/common/types/useFunnel.type.ts
Labels: 🖥️ FE, ✨ Feature, Priority 1

#24 정산 시작, 모임 이름 입력, 비밀번호 설정 페이지 UI 구현
  .eslintrc.cjs
  package.json
  public/svgs/goBackIcon.svg
  public/svgs/selectNewGroupIcon.svg
  public/svgs/selectRecentGroupIcon.svg
  src/App.tsx
  src/Router.tsx
  src/assets/fonts/PretendardVariable.woff2
  src/assets/svgs/GoBackIcon.tsx
  src/assets/svgs/SelectNewGroupIcon.tsx
  src/assets/svgs/SelectRecentGroupIcon.tsx
  src/assets/svgs/index.ts
  src/common/components/header/index.stories.tsx
  src/common/components/header/index.styles.ts
  src/common/components/header/index.tsx
  src/common/components/layout/index.styles.ts
  src/common/components/layout/index.tsx
  src/common/constants/route.ts
  src/main.tsx
  src/pages/groupSetup/groupNameSetup/index.tsx
  src/pages/groupSetup/index.styles.ts
  src/pages/groupSetup/passwordSetup/index.tsx
  src/pages/groupSetup/stores/useGroupSetupStore.ts
  src/pages/main/components/testComponent/index.tsx
  src/pages/main/index.tsx
  src/pages/main/styles/index.styles.ts
  src/pages/main/types/index.ts
  src/pages/selectGroup/index.styles.ts
  src/pages/selectGroup/index.tsx
  src/styles/globalStyles.ts
  tsconfig.json
  yarn.lock
Labels: 🖥️ FE, ✨ Feature

#26 지출 내역 확인 페이지 UI 구현
  package.json
  public/svgs/icon/carbon_edit.svg
  public/svgs/icon/close.svg
  public/svgs/icon/next.svg
  src/assets/svgs/icon/CarbonEdit.tsx
  src/assets/svgs/icon/Close.tsx
  src/assets/svgs/icon/Next.tsx
  src/assets/svgs/icon/index.ts
  src/common/components/Chip.tsx
  src/common/components/Chip/index.styles.ts
  src/common/components/Chip/index.tsx
  src/common/styles/Chip.styles.ts
  src/common/types/axios.d.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/handlers/expense.ts
  src/mocks/utils/enableMocking.ts
  src/pages/create/addBillStep/components/ParticipantChips/index.tsx
  src/pages/create/addExpenseStep/components/DatePicker/index.styles.tsx
  src/pages/create/addExpenseStep/components/DatePicker/index.tsx
  src/pages/create/addExpenseStep/components/FormCard/index.styles.ts
  src/pages/create/addExpenseStep/components/FormCard/index.tsx
  src/pages/create/addExpenseStep/components/FormField/index.styles.ts
  src/pages/create/addExpenseStep/components/FormField/index.tsx
  src/pages/create/addExpenseStep/components/MemberChips/index.styles.ts
  src/pages/create/addExpenseStep/components/MemberChips/index.tsx
  src/pages/create/addExpenseStep/components/NumPad/index.styles.tsx
  src/pages/create/addExpenseStep/components/NumPad/index.tsx
  src/pages/create/addExpenseStep/components/NumPadBottomSheet/index.styles.ts
  src/pages/create/addExpenseStep/components/NumPadBottomSheet/index.tsx
  src/pages/create/addExpenseStep/components/ReadonlyInput/index.tsx
  src/pages/create/addExpenseStep/index.styles.ts
  src/pages/create/addExpenseStep/index.tsx
  src/pages/create/addExpenseStep/utils/numPadController.test.ts
  src/pages/create/addExpenseStep/utils/numPadController.ts
  src/pages/create/confirmStep/components/ExpenseCard/index.styles.ts
  src/pages/create/confirmStep/components/ExpenseCard/index.tsx
  src/pages/create/confirmStep/components/ExpenseCardList/index.tsx
  src/pages/create/confirmStep/hooks/useGetAllExpense.ts
  src/pages/create/confirmStep/index.styles.ts
  src/pages/create/confirmStep/index.tsx
  src/pages/create/index.tsx
  src/pages/create/types/expense.type.ts
  src/pages/create/utils/distributeExpense.test.ts
  src/pages/create/utils/distributeExpense.ts
  src/pages/create/utils/getTotalExpense.ts
  src/service/apis/axios.ts
  src/service/apis/expense.ts
  yarn.lock
Labels: 🖥️ FE, ✨ Feature, Priority 1

#29 컴포넌트 폴더명을 파스칼 케이스로 변경
  src/common/components/Button/Button.stories.ts
  src/common/components/Button/Button.tsx
  src/common/components/Button/button.css
  src/common/components/Header/index.stories.tsx
  src/common/components/Header/index.styles.ts
  src/common/components/Header/index.tsx
  src/common/components/Layout/index.styles.ts
  src/common/components/Layout/index.tsx
Labels: 🖥️ FE, 🐞 Bug

#27 모임 참가자 입력 페이지 UI 구현 및 참가자 추가 컴포넌트 분리
  package.json
  public/svgs/deleteButtonIcon.svg
  src/Router.tsx
  src/assets/pngs/defaultProfileImg.png
  src/assets/svgs/DeleteButtonIcon.tsx
  src/assets/svgs/index.ts
  src/common/components/AddMember/index.tsx
  src/common/components/MemberProfile/index.style.ts
  src/common/components/MemberProfile/index.tsx
  src/common/constants/route.ts
  src/common/types/member.type.ts
  src/common/utils/getRandomColor.ts
  src/pages/groupSetup/groupNameSetup/index.tsx
  src/pages/groupSetup/index.styles.ts
  src/pages/groupSetup/memberSetup/index.tsx
  src/pages/groupSetup/passwordSetup/index.tsx
  src/pages/groupSetup/stores/useGroupSetupStore.ts
  src/pages/selectGroup/index.styles.ts
  yarn.lock
Labels: 🖥️ FE, ✨ Feature, Priority 1

#33 로그인페이지 및 홈페이지 UI 구현
  public/svgs/arrowRightIcon.svg
  public/svgs/logoIcon.svg
  public/svgs/menuIcon.svg
  src/Router.tsx
  src/assets/pngs/CoinImg.png
  src/assets/pngs/LoginHamImg.png
  src/assets/pngs/LoginSuccessImg.png
  src/assets/pngs/LogoImg.png
  src/assets/pngs/MainHamImg.png
  src/assets/svgs/ArrowRightIcon.tsx
  src/assets/svgs/LogoIcon.tsx
  src/assets/svgs/MenuIcon.tsx
  src/assets/svgs/index.ts
  src/common/constants/route.ts
  src/pages/auth/login/index.style.ts
  src/pages/auth/login/index.tsx
  src/pages/auth/loginSuccess/index.style.ts
  src/pages/auth/loginSuccess/index.tsx
  src/pages/home/index.style.ts
  src/pages/home/index.tsx
  src/pages/selectGroup/index.tsx
Labels: 🖥️ FE, ✨ Feature, Priority 1

#31 '지출 입력 - 계좌 입력 - 공유' 플로우에 useFunnel 적용
  package.json
  public/svgs/icon/arrow-left.svg
  src/Router.tsx
  src/assets/svgs/icon/ArrowLeft.tsx
  src/assets/svgs/icon/index.ts
  src/common/components/Header/index.styles.ts
  src/common/components/Header/index.tsx
  src/common/constants/route.ts
  src/common/hooks/useFunnel.ts
  src/common/types/useFunnel.type.ts
  src/pages/create/addExpenseStep/index.tsx
  src/pages/create/index.tsx
  src/pages/createBill/addAccountStep/index.tsx
  src/pages/createBill/addExpenseStep/components/DatePicker/index.styles.tsx
  src/pages/createBill/addExpenseStep/components/DatePicker/index.tsx
  src/pages/createBill/addExpenseStep/components/FormCard/index.styles.ts
  src/pages/createBill/addExpenseStep/components/FormCard/index.tsx
  src/pages/createBill/addExpenseStep/components/FormField/index.styles.ts
  src/pages/createBill/addExpenseStep/components/FormField/index.tsx
  src/pages/createBill/addExpenseStep/components/MemberChips/index.styles.ts
  src/pages/createBill/addExpenseStep/components/MemberChips/index.tsx
  src/pages/createBill/addExpenseStep/components/NumPad/index.styles.tsx
  src/pages/createBill/addExpenseStep/components/NumPad/index.tsx
  src/pages/createBill/addExpenseStep/components/NumPadBottomSheet/index.styles.ts
  src/pages/createBill/addExpenseStep/components/NumPadBottomSheet/index.tsx
  src/pages/createBill/addExpenseStep/components/ReadonlyInput/index.tsx
  src/pages/createBill/addExpenseStep/index.styles.ts
  src/pages/createBill/addExpenseStep/index.tsx
  src/pages/createBill/addExpenseStep/utils/numPadController.test.ts
  src/pages/createBill/addExpenseStep/utils/numPadController.ts
  src/pages/createBill/confirmStep/components/ExpenseCard/index.styles.ts
  src/pages/createBill/confirmStep/components/ExpenseCard/index.tsx
  src/pages/createBill/confirmStep/components/ExpenseCardList/index.tsx
  src/pages/createBill/confirmStep/hooks/useGetAllExpense.ts
  src/pages/createBill/confirmStep/index.styles.ts
  src/pages/createBill/confirmStep/index.tsx
  src/pages/createBill/index.tsx
  src/pages/createBill/shareStep/index.tsx
  src/pages/createBill/types/billContext.type.ts
  src/pages/createBill/types/expense.type.ts
  src/pages/createBill/utils/distributeExpense.test.ts
  src/pages/createBill/utils/distributeExpense.ts
  src/pages/createBill/utils/getTotalExpense.ts
  src/service/apis/expense.ts
  yarn.lock
Labels: 🖥️ FE, ✨ Feature, Priority 1

#35 지출 페이지 디자인 적용
  public/svgs/icon/arrow-right.svg
  public/svgs/icon/calendar.svg
  src/assets/svgs/icon/ArrowRight.tsx
  src/assets/svgs/icon/Calendar.tsx
  src/assets/svgs/icon/index.ts
  src/pages/createBill/addExpenseStep/components/DatePicker/index.styles.tsx
  src/pages/createBill/addExpenseStep/components/DatePicker/index.tsx
  src/pages/createBill/addExpenseStep/components/MemberChips/index.styles.ts
  src/pages/createBill/addExpenseStep/components/NumPad/index.styles.tsx
  src/pages/createBill/addExpenseStep/components/NumPad/index.tsx
  src/pages/createBill/addExpenseStep/components/NumPadBottomSheet/index.styles.ts
  src/pages/createBill/addExpenseStep/components/ReadonlyInput/index.style.ts
  src/pages/createBill/addExpenseStep/components/ReadonlyInput/index.tsx
  src/pages/createBill/addExpenseStep/index.styles.ts
  src/pages/createBill/addExpenseStep/index.tsx
  src/pages/createBill/addExpenseStep/utils/numPadController.ts
  src/pages/createBill/confirmStep/components/ExpenseCard/index.styles.ts
  src/pages/createBill/confirmStep/index.styles.ts
  src/pages/createBill/confirmStep/index.tsx
  src/pages/createBill/utils/getTotalExpense.ts
Labels: 🖥️ FE, 🎨 Design

#36 계좌 입력페이지 UI 구현
  src/common/components/Header/index.styles.ts
  src/pages/createBill/addAccountStep/components/BankNameDrawer/index.style.ts
  src/pages/createBill/addAccountStep/components/BankNameDrawer/index.tsx
  src/pages/createBill/addAccountStep/constants/BankList.ts
  src/pages/createBill/addAccountStep/index.tsx
  src/pages/groupSetup/memberSetup/index.tsx
Labels: 🖥️ FE, ✨ Feature, Priority 1

#39 지출 추가 기능 구현
  src/common/components/Chip/index.tsx
  src/pages/createBill/addExpenseStep/components/FormCard/index.styles.ts
  src/pages/createBill/addExpenseStep/components/FormCard/index.tsx
  src/pages/createBill/addExpenseStep/index.styles.ts
  src/pages/createBill/addExpenseStep/index.tsx
Labels: 🖥️ FE, ✨ Feature, Priority 1

#38 정산 참여자 추가 UI
  src/common/components/AddMember/index.tsx
  src/common/components/MemberProfile/index.style.ts
  src/common/components/MemberProfile/index.tsx
  src/pages/createBill/addExpenseStep/components/FormCard/index.tsx
  src/pages/createBill/addExpenseStep/components/MemberBottomSheet/index.tsx
  src/pages/groupSetup/memberSetup/index.tsx
Labels: 🖥️ FE, ✨ Feature, Priority 1

#44 프론트엔드 배포 및 CI/CD 설정
  .eslintrc.cjs
  .github/workflows/dev-ci-cd.yml
  src/assets/svgs/ArrowRightIcon.tsx
  src/assets/svgs/DeleteButtonIcon.tsx
  src/assets/svgs/GoBackIcon.tsx
  src/assets/svgs/LogoIcon.tsx
  src/assets/svgs/MenuIcon.tsx
  src/assets/svgs/SelectNewGroupIcon.tsx
  src/assets/svgs/SelectRecentGroupIcon.tsx
  src/assets/svgs/icon/ArrowLeft.tsx
  src/assets/svgs/icon/ArrowRight.tsx
  src/assets/svgs/icon/Calendar.tsx
  src/assets/svgs/icon/CarbonEdit.tsx
  src/assets/svgs/icon/Close.tsx
  src/assets/svgs/icon/Next.tsx
  src/common/components/Header/index.stories.tsx
  src/common/components/MemberProfile/index.tsx
  src/common/constants/route.ts
  src/common/types/member.type.ts
  src/common/utils/getRandomColor.ts
  src/pages/auth/login/index.style.ts
  src/pages/auth/login/index.tsx
  src/pages/auth/loginSuccess/index.style.ts
  src/pages/auth/loginSuccess/index.tsx
  src/pages/createBill/addAccountStep/components/BankNameDrawer/index.style.ts
  src/pages/createBill/addAccountStep/components/BankNameDrawer/index.tsx
  src/pages/createBill/addAccountStep/constants/BankList.ts
  src/pages/groupSetup/groupNameSetup/index.tsx
  src/pages/groupSetup/memberSetup/index.tsx
  src/pages/groupSetup/passwordSetup/index.tsx
  src/pages/groupSetup/stores/useGroupSetupStore.ts
  src/pages/home/index.style.ts
  src/pages/home/index.tsx
  src/pages/selectGroup/index.styles.ts
  src/pages/selectGroup/index.tsx
  src/pages/test.tsx
  yarn.lock
Labels: 🖥️ FE, 🌐 Infra

#41 공유 페이지 UI 구현
  src/assets/pngs/Link.png
  src/common/constants/shareFormat.ts
  src/common/types/kakao.d.ts
  src/common/types/share.type.ts
  src/common/utils/copyClipboard.ts
  src/common/utils/initKakaoSDK.ts
  src/common/utils/share.ts
  src/common/utils/shareKakao.ts
  src/pages/createBill/addAccountStep/index.tsx
  src/pages/createBill/index.tsx
  src/pages/createBill/shareStep/components/ShareButton/index.styles.ts
  src/pages/createBill/shareStep/components/ShareButton/index.tsx
  src/pages/createBill/shareStep/components/ShareItemButton/index.styles.ts
  src/pages/createBill/shareStep/components/ShareItemButton/index.tsx
  src/pages/createBill/shareStep/index.styles.ts
  src/pages/createBill/shareStep/index.tsx
Labels: 🖥️ FE, ✨ Feature, Priority 1

#49 공유 페이지 UI 구현 - lint 오류 수정
  src/pages/createBill/shareStep/components/ShareButton/index.tsx
Labels: 🖥️ FE, ✨ Feature, 🐞 Bug, Priority 1

#50 지출 생성, 조회, 삭제 API 연결
  src/common/components/Layout/index.styles.ts
  src/common/queries/expense/useCreateExpense.ts
  src/common/queries/expense/useDeleteExpense.ts
  src/common/queries/expense/useGetAllExpense.ts
  src/common/types/group.type.ts
  src/common/types/member.type.ts
  src/mocks/handlers.ts
  src/mocks/handlers/expense.ts
  src/mocks/handlers/group.ts
  src/mocks/handlers/groupMember.ts
  src/mocks/utils/getIsMocked.ts
  src/pages/createBill/addExpenseStep/index.styles.ts
  src/pages/createBill/addExpenseStep/index.tsx
  src/pages/createBill/confirmStep/components/ExpenseCard/index.styles.ts
  src/pages/createBill/confirmStep/components/ExpenseCard/index.tsx
  src/pages/createBill/confirmStep/components/ExpenseCardList/index.styles.ts
  src/pages/createBill/confirmStep/components/ExpenseCardList/index.tsx
  src/pages/createBill/confirmStep/index.styles.ts
  src/pages/createBill/confirmStep/index.tsx
  src/pages/createBill/confirmStep/utils/categrizeExpensesByDateWithIndex.ts
  src/pages/createBill/types/expense.type.ts
  src/service/apis/expense.ts
  src/service/apis/group.ts
Labels: 🖥️ FE, ✨ Feature, Priority 1

#53 비회원 로그인 및 정산 모임 생성 API 연결, axiosInstance 설정 추가
  src/App.tsx
  src/Router.tsx
  src/common/queries/auth/useGetGuestToken.ts
  src/common/queries/group/usePostCreateGroup.ts
  src/common/types/group.type.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/handlers/auth.ts
  src/mocks/handlers/group.ts
  src/pages/auth/login/index.style.ts
  src/pages/auth/login/index.tsx
  src/pages/groupSetup/passwordSetup/index.tsx
  src/service/apis/auth.ts
  src/service/apis/axios.ts
  src/service/apis/group.ts
  src/service/apis/user/index.ts
Labels: 🖥️ FE, ✨ Feature, Priority 1

#60 모임 참가자, 계좌 입력 관련 API 연결
  package.json
  src/App.tsx
  src/common/components/AddMember/index.tsx
  src/common/components/MemberProfile/index.tsx
  src/common/queries/group/usePostCreateGroup.ts
  src/common/queries/group/usePutUpdateAccount.ts
  src/common/queries/groupMembers/usePostCreateGroupMembers.ts
  src/common/types/group.type.ts
  src/common/types/member.type.ts
  src/mocks/handlers.ts
  src/mocks/handlers/expense.ts
  src/mocks/handlers/group.ts
  src/mocks/handlers/groupMember.ts
  src/pages/createBill/addAccountStep/index.tsx
  src/pages/createBill/components/MemberBottomSheet/index.tsx
  src/pages/groupSetup/memberSetup/index.tsx
  src/pages/groupSetup/stores/useGroupSetupStore.ts
  src/service/apis/axios.ts
  src/service/apis/expense.ts
  src/service/apis/group.ts
  src/service/apis/groupMembers.ts
  yarn.lock
Labels: 🖥️ FE, ✨ Feature, Priority 1

#61 공통 컴포넌트 Button과 ButtonGroup 구현
  src/common/components/Button/Button.stories.ts
  src/common/components/Button/Button.tsx
  src/common/components/Button/button.css
  src/common/components/Button/index.stories.tsx
  src/common/components/Button/index.styles.ts
  src/common/components/Button/index.tsx
  src/common/components/Button/index.type.ts
  src/common/components/ButtonGroup/index.stories.tsx
  src/common/components/ButtonGroup/index.styles.ts
  src/common/components/ButtonGroup/index.tsx
  src/common/components/ButtonGroup/index.type.ts
  src/common/components/Text/index.styles.tsx
Labels: 🖥️ FE, 🎨 Design, Priority 1

#65 공통 컴포넌트 Input과 Chip 구현
  .storybook/main.ts
  package.json
  public/svgs/icon/dummy.svg
  src/assets/svgs/icon/Dummy.tsx
  src/assets/svgs/icon/index.ts
  src/common/components/Chip/index.stories.tsx
  src/common/components/Chip/index.styles.ts
  src/common/components/Chip/index.tsx
  src/common/components/Chip/index.type.ts
  src/common/components/Input/index.stories.tsx
  src/common/components/Input/index.styles.ts
  src/common/components/Input/index.tsx
  src/common/components/InputGroup/index.stories.tsx
  src/common/components/InputGroup/index.styles.ts
  src/common/components/InputGroup/index.tsx
  src/common/components/StatusChip/index.stories.tsx
  src/common/components/StatusChip/index.styles.ts
  src/common/components/StatusChip/index.tsx
  src/common/components/StatusChip/index.type.ts
  src/common/components/Tag/index.stories.ts
  src/common/components/Tag/index.styles.ts
  src/common/components/Tag/index.tsx
  src/pages/createBill/components/MemberChips/index.tsx
  src/pages/createBill/confirmStep/components/ExpenseCard/index.tsx
  yarn.lock
Labels: 🖥️ FE, 🎨 Design, Priority 1

#69 공통 컴포넌트 DatePicker, NumPad, Tab, StarChip 구현
  public/svgs/icon/btn-shortcut.svg
  public/svgs/icon/star.svg
  src/assets/svgs/icon/BtnShortcut.tsx
  src/assets/svgs/icon/Star.tsx
  src/assets/svgs/icon/index.ts
  src/common/components/Button/index.styles.ts
  src/common/components/DatePicker/index.stories.tsx
  src/common/components/DatePicker/index.styles.ts
  src/common/components/DatePicker/index.tsx
  src/common/components/NumPad/index.stories.tsx
  src/common/components/NumPad/index.styles.ts
  src/common/components/NumPad/index.tsx
  src/common/components/NumPad/numPadController.test.ts
  src/common/components/NumPad/numPadController.tsx
  src/common/components/StarChip/index.stories.tsx
  src/common/components/StarChip/index.styles.ts
  src/common/components/StarChip/index.tsx
  src/common/components/Tabs/index.stories.tsx
  src/common/components/Tabs/index.styles.ts
  src/common/components/Tabs/index.tsx
  src/pages/createBill/components/DatePicker/index.styles.tsx
  src/pages/createBill/components/DatePicker/index.tsx
  src/pages/createBill/components/FormCard/index.tsx
  src/pages/createBill/components/NumPad/index.styles.tsx
  src/pages/createBill/components/NumPad/index.tsx
  src/pages/createBill/components/NumPadBottomSheet/index.styles.ts
  src/pages/createBill/components/NumPadBottomSheet/index.tsx
  src/pages/createBill/components/ReadonlyInput/index.style.ts
  src/pages/createBill/components/ReadonlyInput/index.tsx
  src/pages/createBill/utils/numPadController.ts
  src/stories/colors.mdx
  src/styles/theme.ts
Labels: 🖥️ FE, 🎨 Design, Priority 1

#67 공통 컴포넌트 Toast 구현
  .github/workflows/publish-storybook.yml
  package.json
  src/App.tsx
  src/common/components/Toast/index.stories.tsx
  src/common/components/Toast/index.style.ts
  src/common/components/Toast/index.tsx
  src/common/components/Toast/index.type.ts
  src/common/hooks/useFunnel.ts
  src/pages/createBill/shareStep/components/ShareButton/index.tsx
  vite.config.ts
  yarn.lock
Labels: 🖥️ FE, 🎨 Design

#72 공통 컴포넌트 Modal 구현
  .storybook/preview-body.html
  index.html
  src/common/components/Modal/index.stories.tsx
  src/common/components/Modal/index.style.ts
  src/common/components/Modal/index.tsx
  src/pages/createBill/createExpenseStep/index.tsx
Labels: 🖥️ FE, 🎨 Design

#74 받을 정산 세부 - 전체 지출내역 UI 구현
  src/Router.tsx
  src/common/components/Chip/index.styles.ts
  src/common/components/Header/index.tsx
  src/common/components/Text/index.styles.tsx
  src/common/components/Text/index.tsx
  src/common/constants/route.ts
  src/common/loaders/checkAuth.ts
  src/common/loaders/groupTokenUrlLoader.ts
  src/common/loaders/index.ts
  src/common/queries/expense/useGetExpenseDetail.ts
  src/common/types/group.type.ts
  src/mocks/handlers/expense.ts
  src/pages/billDetail/components/ExpenseTimeline/index.styles.ts
  src/pages/billDetail/components/ExpenseTimeline/index.tsx
  src/pages/billDetail/components/ExpenseTimelineContent/index.styles.ts
  src/pages/billDetail/components/ExpenseTimelineContent/index.tsx
  src/pages/billDetail/index.styles.ts
  src/pages/billDetail/index.tsx
  src/pages/createBill/types/expense.type.ts
  src/service/apis/expense.ts
  src/styles/bottomButton.styles.ts
Labels: 🖥️ FE, ✨ Feature, Priority 1

#76 공통 컴포넌트 - 바텀시트 구현
  .storybook/preview-body.html
  index.html
  package.json
  public/pngs/banks/bankName=IBK기업.png
  public/pngs/banks/bankName=KB국민.png
  public/pngs/banks/bankName=KB증권.png
  public/pngs/banks/bankName=KDB산업.png
  public/pngs/banks/bankName=KEB외환.png
  public/pngs/banks/bankName=NH농협.png
  public/pngs/banks/bankName=NH투자증권.png
  public/pngs/banks/bankName=SBI저축.png
  public/pngs/banks/bankName=SC제일.png
  public/pngs/banks/bankName=경남.png
  public/pngs/banks/bankName=광주.png
  public/pngs/banks/bankName=대구.png
  public/pngs/banks/bankName=부산.png
  public/pngs/banks/bankName=산림조합.png
  public/pngs/banks/bankName=새마을.png
  public/pngs/banks/bankName=수협.png
  public/pngs/banks/bankName=신한.png
  public/pngs/banks/bankName=신협.png
  public/pngs/banks/bankName=씨티.png
  public/pngs/banks/bankName=우리.png
  public/pngs/banks/bankName=우체국.png
  public/pngs/banks/bankName=저축은행.png
  public/pngs/banks/bankName=전북.png
  public/pngs/banks/bankName=제주.png
  public/pngs/banks/bankName=카카오뱅크.png
  public/pngs/banks/bankName=케이뱅크.png
  public/pngs/banks/bankName=토스뱅크.png
  public/pngs/banks/bankName=하나.png
  public/pngs/banks/bankName=한국투자증권.png
  src/common/components/AddMember/index.tsx
  src/common/components/BottomSheet/index.stories.tsx
  src/common/components/BottomSheet/index.style.ts
  src/common/components/BottomSheet/index.tsx
  src/common/components/Button/index.styles.ts
  src/common/components/Header/index.styles.ts
  src/common/components/Input/index.styles.ts
  src/common/components/InputGroup/index.styles.ts
  src/common/components/Modal/index.tsx
  src/common/components/NumPad/index.styles.ts
  src/pages/createBill/addAccountStep/components/BankNameDrawer/index.style.ts
  src/pages/createBill/addAccountStep/components/BankNameDrawer/index.tsx
  src/pages/createBill/addAccountStep/constants/BankList.ts
  src/pages/createBill/addAccountStep/utils/BankList.ts
  src/pages/createBill/components/MemberBottomSheet/index.tsx
  src/pages/createBill/components/NumPadBottomSheet/index.styles.ts
  src/pages/createBill/components/NumPadBottomSheet/index.tsx
  yarn.lock
Labels: 🖥️ FE, 🎨 Design, Priority 1

#78 지출 폼 UI 변경
  src/Router.tsx
  src/common/components/Alert/index.stories.tsx
  src/common/components/Alert/index.styles.ts
  src/common/components/Alert/index.tsx
  src/common/components/Alert/index.type.ts
  src/common/components/NumPad/index.styles.ts
  src/common/components/NumberInput/index.stories.tsx
  src/common/components/NumberInput/index.styles.ts
  src/common/components/NumberInput/index.tsx
  src/common/loader/getGroupManagerAuth.ts
  src/common/types/member.type.ts
  src/mocks/handlers/expense.ts
  src/pages/createBill/addExpenseStep/index.tsx
  src/pages/createBill/components/FormCard/index.styles.ts
  src/pages/createBill/components/FormCard/index.tsx
  src/pages/createBill/components/FormField/index.styles.ts
  src/pages/createBill/components/FormField/index.tsx
  src/pages/createBill/components/MemberChips/index.styles.ts
  src/pages/createBill/components/MemberChips/index.tsx
  src/pages/createBill/components/MemberExpenses/index.styles.ts
  src/pages/createBill/components/MemberExpenses/index.tsx
  src/pages/createBill/components/NumPadBottomSheet/index.styles.ts
  src/pages/createBill/components/NumPadBottomSheet/index.tsx
  src/pages/createBill/confirmStep/components/ExpenseCard/index.tsx
  src/pages/createBill/confirmStep/components/ExpenseCardList/index.tsx
  src/pages/createBill/confirmStep/index.tsx
  src/pages/createBill/createExpenseStep/index.styles.ts
  src/pages/createBill/createExpenseStep/index.tsx
  src/pages/createBill/editExpenseStep/index.tsx
  src/pages/createBill/hooks/useAddExpenseFormArray.ts
  src/pages/createBill/index.tsx
  src/pages/createBill/types/billContext.type.ts
  src/pages/createBill/types/expense.type.ts
  src/pages/createBill/utils/distributeExpense.test.ts
  src/pages/createBill/utils/distributeExpense.ts
  src/pages/createBill/utils/getTotalExpense.ts
  src/service/apis/expense.ts
Labels: 🖥️ FE, ✨ Feature, 🎨 Design, Priority 1

#82 공통 컴포넌트 - CurvedProgressBar, DefaultProgressBar, Divider
  package.json
  src/assets/pngs/moddoFace.png
  src/assets/svgs/icon/Crown.tsx
  src/common/components/Chip/index.styles.ts
  src/common/components/CurvedProgressBar/index.stories.tsx
  src/common/components/CurvedProgressBar/index.style.ts
  src/common/components/CurvedProgressBar/index.tsx
  src/common/components/DefaultProgressBar/index.stories.tsx
  src/common/components/DefaultProgressBar/index.style.ts
  src/common/components/DefaultProgressBar/index.tsx
  src/common/components/Divider/index.stories.tsx
  src/common/components/Divider/index.style.ts
  src/common/components/Divider/index.tsx
  src/common/utils/ChangingProgressProvider.ts
  src/pages/billDetail/index.styles.ts
  src/pages/billDetail/index.tsx
  vite.config.ts
  yarn.lock
Labels: 🖥️ FE, 🎨 Design, Priority 1

#81 그룹 생성 플로우 API 모킹 제거
  src/common/components/AddMember/index.tsx
  src/common/constants/route.ts
  src/common/queries/group/useGetGroupBasicInfo.ts
  src/common/queries/groupMembers/useAddGroupMember.ts
  src/common/queries/groupMembers/useDeleteGroupMember.ts
  src/pages/createBill/createExpenseStep/index.tsx
  src/pages/createBill/hooks/useAddExpenseFormArray.ts
  src/pages/groupSetup/memberSetup/index.tsx
  src/service/apis/auth.ts
  src/service/apis/group.ts
  src/service/apis/groupMembers.ts
Labels: 🖥️ FE, ✨ Feature, Priority 1

#84 공유 페이지 기능 고도화
  package.json
  public/svgs/icon/copy.svg
  public/svgs/logo/Slack.svg
  public/svgs/logo/kakaotalk.svg
  src/assets/svgs/icon/Copy.tsx
  src/assets/svgs/logo/Kakaotalk.tsx
  src/assets/svgs/logo/Slack.tsx
  src/assets/svgs/logo/index.ts
  src/common/components/Button/index.styles.ts
  src/common/components/DescriptionField/index.tsx
  src/common/constants/route.ts
  src/common/utils/generateShareLink.ts
  src/common/utils/share.ts
  src/pages/createBill/index.tsx
  src/pages/createBill/qrStep/index.styles.ts
  src/pages/createBill/qrStep/index.tsx
  src/pages/createBill/shareStep/components/ShareButton/index.styles.ts
  src/pages/createBill/shareStep/components/ShareButton/index.tsx
  src/pages/createBill/shareStep/components/ShareItemButton/index.styles.ts
  src/pages/createBill/shareStep/components/ShareItemButton/index.tsx
  src/pages/createBill/shareStep/index.styles.ts
  src/pages/createBill/shareStep/index.tsx
  yarn.lock
Labels: 🖥️ FE, ✨ Feature, Priority 1

#88 빌드 시 환경변수 추가
  .github/workflows/dev-ci-cd.yml
Labels: 🐞 Bug

#86 지출 생성, 계좌 추가 API 모킹 제거
  src/common/components/AddMember/index.tsx
  src/common/components/Button/index.tsx
  src/common/queries/expense/useCreateExpense.ts
  src/common/queries/expense/useDeleteExpense.ts
  src/common/queries/expense/useUpdateExpense.ts
  src/common/queries/group/usePutUpdateAccount.ts
  src/mocks/handlers/expense.ts
  src/pages/createBill/addAccountStep/index.tsx
  src/pages/createBill/addExpenseStep/index.tsx
  src/pages/createBill/components/MemberBottomSheet/index.tsx
  src/pages/createBill/components/MemberExpenses/index.tsx
  src/pages/createBill/components/NumPadBottomSheet/index.tsx
  src/pages/createBill/confirmStep/components/ExpenseCard/index.tsx
  src/pages/createBill/confirmStep/index.tsx
  src/pages/createBill/createExpenseStep/index.tsx
  src/pages/createBill/editExpenseStep/index.tsx
  src/pages/createBill/hooks/useAddExpenseFormArray.ts
  src/pages/createBill/types/expense.type.ts
  src/pages/groupSetup/memberSetup/index.tsx
  src/service/apis/expense.ts
  src/service/apis/group.ts
Labels: 🖥️ FE, ✨ Feature, Priority 1

#89 캐릭터 획득 UI
  public/pngs/angle-moddo.png
  src/Router.tsx
  src/common/components/ButtonGroup/index.styles.ts
  src/common/constants/character.ts
  src/common/constants/route.ts
  src/common/loaders/groupTokenUrlLoader.ts
  src/common/queries/image/useGetRandomCharacter.ts
  src/common/types/character.ts
  src/pages/billDetail/characterShare/index.styles.ts
  src/pages/billDetail/characterShare/index.tsx
  src/pages/billDetail/components/CharacterBottomSheet/index.styles.ts
  src/pages/billDetail/components/CharacterBottomSheet/index.tsx
  src/pages/billDetail/index.tsx
  src/service/apis/image.ts
Labels: 🖥️ FE, ✨ Feature, Priority 1

#91 받을 정산 Header UI 구현 및 getGroupHeader API 연결
  src/assets/pngs/CryingModdoFace.png
  src/common/components/CurvedProgressBar/index.tsx
  src/common/components/DescriptionField/index.tsx
  src/common/components/Divider/index.tsx
  src/common/components/Header/index.styles.ts
  src/common/components/Header/index.tsx
  src/common/queries/group/useGetGroupHeader.ts
  src/common/types/group.type.ts
  src/pages/billDetail/components/ExpenseTimeHeader/index.style.ts
  src/pages/billDetail/components/ExpenseTimeHeader/index.tsx
  src/pages/billDetail/components/ExpenseTimeHeader/index.type.ts
  src/pages/billDetail/index.styles.ts
  src/pages/billDetail/index.tsx
  src/pages/billDetail/utils/getFormatDate.ts
  src/service/apis/group.ts
Labels: 🖥️ FE, ✨ Feature

#93 지출 추가 페이지의 참여자 추가 기능 보완
  src/common/components/BottomSheet/index.tsx
  src/pages/createBill/addExpenseStep/index.tsx
  src/pages/createBill/components/FormCard/index.tsx
  src/pages/createBill/components/MemberBottomSheet/index.tsx
  src/pages/createBill/createExpenseStep/index.tsx
  src/pages/createBill/editExpenseStep/index.tsx
  src/pages/createBill/hooks/useAddExpenseFormArray.ts
Labels: 🖥️ FE, 🐞 Bug

#98 지출 추가 페이지 UI 수정
  src/common/components/DatePicker/index.tsx
  src/common/components/Input/index.tsx
  src/common/components/NumPad/index.styles.ts
  src/common/components/NumberInput/index.tsx
  src/common/loaders/groupTokenUrlLoader.ts
Labels: 🖥️ FE, 🐞 Bug

#102 지출 참여자 관련 QA 반영
  src/common/queries/groupMembers/useDeleteGroupMember.ts
  src/pages/createBill/addExpenseStep/index.tsx
  src/pages/createBill/components/FormCard/index.tsx
  src/pages/createBill/components/MemberExpenses/index.tsx
  src/pages/createBill/createExpenseStep/index.tsx
  src/pages/createBill/editExpenseStep/index.tsx
  src/pages/createBill/hooks/useAddExpenseFormArray.ts
Labels: 🖥️ FE, 🐞 Bug

#103 디자인 관련 QA 반영 (모임이름~계좌입력)
  public/fonts/PretendardVariable.woff2
  src/common/components/AddMember/index.styles.ts
  src/common/components/AddMember/index.tsx
  src/common/components/DescriptionField/index.styles.ts
  src/common/components/DescriptionField/index.tsx
  src/common/components/Input/index.tsx
  src/common/components/MemberProfile/index.tsx
  src/common/components/Text/index.styles.tsx
  src/pages/createBill/addAccountStep/index.styles.ts
  src/pages/createBill/addAccountStep/index.tsx
  src/pages/createBill/addExpenseStep/index.styles.ts
  src/pages/createBill/addExpenseStep/index.tsx
  src/pages/createBill/confirmStep/components/ExpenseCard/index.styles.ts
  src/pages/createBill/confirmStep/components/ExpenseCard/index.tsx
  src/pages/createBill/confirmStep/components/ExpenseCardList/index.styles.ts
  src/pages/createBill/confirmStep/components/ExpenseCardList/index.tsx
  src/pages/createBill/confirmStep/index.styles.ts
  src/pages/createBill/confirmStep/index.tsx
  src/pages/createBill/createExpenseStep/index.styles.ts
  src/pages/createBill/createExpenseStep/index.tsx
  src/pages/createBill/editExpenseStep/index.styles.ts
  src/pages/createBill/editExpenseStep/index.tsx
  src/pages/groupSetup/groupNameSetup/index.tsx
  src/pages/groupSetup/index.styles.ts
  src/pages/groupSetup/memberSetup/index.tsx
  src/pages/groupSetup/passwordSetup/index.tsx
  src/styles/bottomButton.styles.ts
  src/styles/globalStyles.ts
Labels: 🖥️ FE, 🎨 Design

#104 받을 정산 페이지 API 연결 및 정산 완료 로직 구현
  index.html
  src/assets/pngs/banks/bankName=IBK기업.png
  src/assets/pngs/banks/bankName=KB국민.png
  src/assets/pngs/banks/bankName=KB증권.png
  src/assets/pngs/banks/bankName=KDB산업.png
  src/assets/pngs/banks/bankName=KEB외환.png
  src/assets/pngs/banks/bankName=NH농협.png
  src/assets/pngs/banks/bankName=NH투자증권.png
  src/assets/pngs/banks/bankName=SBI저축.png
  src/assets/pngs/banks/bankName=SC제일.png
  src/assets/pngs/banks/bankName=경남.png
  src/assets/pngs/banks/bankName=광주.png
  src/assets/pngs/banks/bankName=대구.png
  src/assets/pngs/banks/bankName=부산.png
  src/assets/pngs/banks/bankName=산림조합.png
  src/assets/pngs/banks/bankName=새마을.png
  src/assets/pngs/banks/bankName=수협.png
  src/assets/pngs/banks/bankName=신한.png
  src/assets/pngs/banks/bankName=신협.png
  src/assets/pngs/banks/bankName=씨티.png
  src/assets/pngs/banks/bankName=우리.png
  src/assets/pngs/banks/bankName=우체국.png
  src/assets/pngs/banks/bankName=저축은행.png
  src/assets/pngs/banks/bankName=전북.png
  src/assets/pngs/banks/bankName=제주.png
  src/assets/pngs/banks/bankName=카카오뱅크.png
  src/assets/pngs/banks/bankName=케이뱅크.png
  src/assets/pngs/banks/bankName=토스뱅크.png
  src/assets/pngs/banks/bankName=하나.png
  src/assets/pngs/banks/bankName=한국투자증권.png
  src/assets/svgs/icon/Confirm.tsx
  src/common/components/StatusChip/index.styles.ts
  src/common/components/Toast/index.style.ts
  src/common/queries/groupMembers/useUpdatePaymentStatus.ts
  src/common/types/groupMember.ts
  src/pages/billDetail/components/ExpenseMembers/index.style.ts
  src/pages/billDetail/components/ExpenseMembers/index.tsx
  src/pages/billDetail/components/ExpenseTimeHeader/index.tsx
  src/pages/billDetail/index.tsx
  src/pages/createBill/addAccountStep/utils/BankList.ts
  src/service/apis/groupMembers.ts
Labels: 🖥️ FE, ✨ Feature

#107 은행 로고 이미지 오류 수정
  public/pngs/banks/bankName=IBK기업.png
  public/pngs/banks/bankName=KB국민.png
  public/pngs/banks/bankName=KB증권.png
  public/pngs/banks/bankName=KDB산업.png
  public/pngs/banks/bankName=KEB외환.png
  public/pngs/banks/bankName=NH농협.png
  public/pngs/banks/bankName=NH투자증권.png
  public/pngs/banks/bankName=SBI저축.png
  public/pngs/banks/bankName=SC제일.png
  public/pngs/banks/bankName=경남.png
  public/pngs/banks/bankName=광주.png
  public/pngs/banks/bankName=대구.png
  public/pngs/banks/bankName=부산.png
  public/pngs/banks/bankName=산림조합.png
  public/pngs/banks/bankName=새마을.png
  public/pngs/banks/bankName=수협.png
  public/pngs/banks/bankName=신한.png
  public/pngs/banks/bankName=신협.png
  public/pngs/banks/bankName=씨티.png
  public/pngs/banks/bankName=우리.png
  public/pngs/banks/bankName=우체국.png
  public/pngs/banks/bankName=저축은행.png
  public/pngs/banks/bankName=전북.png
  public/pngs/banks/bankName=제주.png
  public/pngs/banks/bankName=카카오뱅크.png
  public/pngs/banks/bankName=케이뱅크.png
  public/pngs/banks/bankName=토스뱅크.png
  public/pngs/banks/bankName=하나.png
  public/pngs/banks/bankName=한국투자증권.png
  src/common/constants/banks.ts
  src/pages/createBill/addAccountStep/components/BankNameDrawer/index.tsx
Labels: 🖥️ FE, 🐞 Bug

#110 캐릭터 API 연결과 디자인 적용
  src/common/constants/character.ts
  src/common/queries/image/useGetCharacter.ts
  src/common/queries/image/useGetRandomCharacter.ts
  src/common/types/character.ts
  src/pages/billDetail/characterShare/index.styles.ts
  src/pages/billDetail/characterShare/index.tsx
  src/pages/billDetail/components/CharacterBottomSheet/index.tsx
  src/pages/billDetail/components/ExpenseTimeHeader/index.tsx
  src/service/apis/image.ts
Labels: 🖥️ FE, ✨ Feature

#113 QA 2차 반영(특정 상황에서 groupSetup 상태 초기화, 모달 창 배경색 설정, HomeExpenseItem 컴포넌트 추가)
  src/common/components/DefaultProgressBar/index.style.ts
  src/common/components/Modal/index.style.ts
  src/pages/billDetail/index.tsx
  src/pages/createBill/createExpenseStep/index.tsx
  src/pages/groupSetup/stores/useGroupSetupStore.ts
  src/pages/home/components/HomeExpenseItem/index.style.ts
  src/pages/home/components/HomeExpenseItem/index.tsx
  src/pages/home/index.style.ts
  src/pages/home/index.tsx
  src/pages/selectGroup/index.tsx
Labels: 🖥️ FE, 🐞 Bug, Priority 1
