Repository dnd-side-project/dnd-12th-7-frontend, pull requests merged in 2025-03, with the labels that each got.

#116 jira - pr 연결 github action 추가
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-review-manager.yml
Labels: 🖥️ FE, ⚙️ Setting

#117 1-2순위 오류 해결(모달 창 height 에러, 은행 바텀시트 grid로 변경, 로티 시간 축소, 유저 프로필 색 에러) 및 ci/cd 정상화
  .github/workflows/dev-ci-cd.yml
  src/common/components/AddMember/index.tsx
  src/common/components/Lottie/index.styles.ts
  src/common/components/Lottie/index.tsx
  src/common/components/MemberProfile/index.style.ts
  src/common/components/MemberProfile/index.tsx
  src/common/components/Modal/index.style.ts
  src/pages/auth/login/index.tsx
  src/pages/billDetail/components/ExpenseMembers/index.tsx
  src/pages/billDetail/components/ExpenseTimeHeader/index.tsx
  src/pages/createBill/addAccountStep/components/BankNameDrawer/index.style.ts
  src/pages/createBill/addAccountStep/components/BankNameDrawer/index.tsx
  src/pages/onboarding/index.style.ts
  src/pages/onboarding/index.tsx
Labels: 🖥️ FE, 🐞 Bug

#118 모임 생성, 지출 생성 단계에 funnel 구조 적용
  package.json
  src/Router.tsx
  src/common/components/AddMember/index.tsx
  src/common/constants/route.ts
  src/common/constants/storageKey.ts
  src/common/hooks/useFunnel.ts
  src/common/hooks/useLocalStorage.ts
  src/common/queries/expense/useCreateExpense.ts
  src/common/queries/expense/useUpdateExpense.ts
  src/common/queries/group/usePostCreateGroup.ts
  src/common/types/useFunnel.type.ts
  src/pages/billDetail/index.tsx
  src/pages/createBill/addAccountStep/index.tsx
  src/pages/createBill/addExpenseStep/index.tsx
  src/pages/createBill/components/MemberBottomSheet/index.tsx
  src/pages/createBill/confirmStep/components/ExpenseCard/index.tsx
  src/pages/createBill/confirmStep/components/ExpenseCardList/index.tsx
  src/pages/createBill/confirmStep/index.tsx
  src/pages/createBill/createExpenseStep/index.tsx
  src/pages/createBill/editExpenseStep/index.tsx
  src/pages/createBill/index.tsx
  src/pages/createBill/qrStep/index.tsx
  src/pages/createBill/shareStep/index.tsx
  src/pages/createBill/types/billContext.type.ts
  src/pages/createBill/types/funnel.type.ts
  src/pages/groupSetup/groupNameSetup/index.tsx
  src/pages/groupSetup/index.tsx
  src/pages/groupSetup/memberSetup/index.tsx
  src/pages/groupSetup/passwordSetup/index.tsx
  src/pages/groupSetup/stores/useGroupSetupStore.ts
  src/pages/selectGroup/index.tsx
  src/service/apis/group.ts
  yarn.lock
Labels: 🖥️ FE, 🛠️ Refactor
